project:
  type: website

website:
  title: "IPSE"
  open-graph: true
  twitter-card: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exec-summary.qmd
        text: Research Findings
      - href: slides.qmd
        text: Presentation
      - href: shiny-app.qmd
        text: Interactive App
      - href: publications.qmd
        text: Publications
    right:
      - href: code-repos.qmd
        text: Open Research
        icon: github
      - href: download-report.qmd
        text: Download the Report
        icon: file-earmark-arrow-down-fill
  favicon: img/favicon.svg
  page-footer: 
    left: Copyright 2024 Calum Webb
    right: Postdoctoral Fellowship PF21\210024
    center: | 
      ![](img/BA_Primary-Logo-White.svg){width=75px} &nbsp; &nbsp; &nbsp; 
      ![](img/UOSLogo_Primary_White_RGB.svg){width=75px}
  
format:
  html:
    theme: 
      - minty
      - custom.scss 
    toc: true
    fontcolor: "#f8f8f8"
    linkcolor: "#FC9C19"
    page-layout: article
    
editor: source

