---
title: "IPSE App"
image: img/la-variation.svg
toc: false
about:
  template: trestles
---


# Explore Local Authority variation using the IPSE Shiny App

This research used multilevel modelling with random slopes in order to estimate differential predicted effects of increased spending on child welfare interventions depending on the local authority children's services that received the funding. An interactive app that works within your browser has been created to facilitate the exploration of these findings. The app can be accessed by clicking [here](){target="_blank"}.

****

It is important to remember that these differences **only** relate to the predicted impact that spending has. They do not tell us anything about the quality of the outcomes for the children who experience a child welfare intervention, or who are able to stay at home safely with their families, nor do they tell us about the quality of the service they receive. Further, the research found that local authorities often experience impacts of spending at different 'stages' of intervention, so while one local authority's spending may have little impact on rates of children in care, it may have much greater 'upstream' impact resolving risks to children's health or development (child in need status) or reducing the risks that might have led to a child protection plan. 

Further, spending that is associated with greater decreases in intervention rates, suggesting that it is very effective for reducing needs and risks, can be a double-edged sword for children's services due to the more significant role these services play. When services have been cut in these local authorities we expect their rates of intervention to increase more dramatically. Services that have 'weaker' effects may therefore not be offering *worse* preventative and supportive services, but may have had to become more resilient or change their thresholds more to manage with the near-universal cuts to local authority spending on preventative services over the time period. 

**As such, differences between local authorities should not be used to judge the quality of the provision preventative and supportive services**. Rather, these findings can be used to identify helpful cross-service learning opportunities, as well as sites for purposive qualitative research. 
